Class {
	#name : #RSSelectionMode,
	#superclass : #Object,
	#classVars : [
		'RS_SELECTION_BROWSE',
		'RS_SELECTION_MULTIPLE',
		'RS_SELECTION_NONE',
		'RS_SELECTION_SINGLE'
	],
	#category : #'Spec-Roassal3-Shapes-Widget-Tree'
}

{ #category : #'as yet unclassified' }
RSSelectionMode class >> RS_SELECTION_BROWSE [
	^ RS_SELECTION_BROWSE
]

{ #category : #'as yet unclassified' }
RSSelectionMode class >> RS_SELECTION_MULTIPLE [
	^ RS_SELECTION_MULTIPLE
]

{ #category : #'as yet unclassified' }
RSSelectionMode class >> RS_SELECTION_SINGLE [
	^ RS_SELECTION_SINGLE
]
